<a href="https://colab.research.google.com/github/zaidanyahya/TensorFlowCourse/blob/master/Module_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing TensorFLow

In [4]:
%tensorflow_version 2.x
import tensorflow as tf

#Tensors

###Creating Tensor

In [11]:
string = tf.Variable("this is string", tf.string)
number = tf.Variable("123", tf.int16)
floating = tf.Variable(3.14, tf.float64)

print(string)
print(number)
print(floating)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is string'>
<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'123'>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.14>


###Rank/Degree of Tensor

In [23]:
rank1_tensor = tf.Variable(["this", "is", "zaidan"], tf.string)
rank2_tensor = tf.Variable([["this", "is", "fisrt"],["this", "is", "second"]], tf.string)

print(rank1_tensor)
print(rank2_tensor)

<tf.Variable 'Variable:0' shape=(3,) dtype=string, numpy=array([b'this', b'is', b'zaidan'], dtype=object)>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=string, numpy=
array([[b'this', b'is', b'fisrt'],
       [b'this', b'is', b'second']], dtype=object)>


###Determine the rank of tensor

In [14]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [15]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

###Shape of Tensor

In [24]:
rank1_tensor.shape

TensorShape([3])

In [17]:
rank2_tensor.shape

TensorShape([2, 3])

###Changing Shape

In [41]:
tensor1 = tf.ones([2,2,4])  #Creates a tensor with all elements set to one (1).
tensor2 = tf.reshape(tensor1, [2,4,2])  #Reshapes a tensor
tensor3 = tf.reshape(tensor2, [4, -1])  # -1 tells the tensor to calculate the 
                                        # size of the dimansion in that place



In [40]:
print(tensor1)
print("---------------------------------------------------")
print(tensor2)
print("---------------------------------------------------")
print(tensor3)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]], shape=(2, 2, 4), dtype=int32)
---------------------------------------------------
tf.Tensor(
[[[1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]]], shape=(2, 4, 2), dtype=int32)
---------------------------------------------------
tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(4, 4), dtype=int32)
